# Generated by Django 4.0 on 2024-09-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
