# Generated by Django 4.0 on 2024-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.TextField(default='destiny woeimietimi', max_length=254),
            preserve_default=False,
        ),
    ]
