# Generated by Django 4.0 on 2024-09-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
