# Generated by Django 4.0 on 2024-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2')], max_length=100)),
                ('customer_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], max_length=100)),
                ('payment_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal')], max_length=100)),
                ('purchase_order_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=255)),
                ('nearest_landmark', models.CharField(max_length=255)),
                ('type_of_order', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('social_media', models.CharField(blank=True, max_length=50, null=True)),
                ('social_media_handle', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mailing_address', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('mailing_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('agree', models.BooleanField(default=False)),
            ],
        ),
    ]
