# Generated by Django 4.0 on 2024-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_fx', models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], max_length=50)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=50)),
                ('transaction_number', models.CharField(max_length=50)),
                ('sender_title', models.CharField(max_length=50)),
                ('sender_surname', models.CharField(max_length=50)),
                ('sender_first_name', models.CharField(max_length=50)),
                ('sender_other_names', models.CharField(blank=True, max_length=50, null=True)),
                ('sender_address', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_amount_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('NGN', 'NGN')], max_length=3)),
                ('sender_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver_title', models.CharField(max_length=50)),
                ('receiver_surname', models.CharField(max_length=50)),
                ('receiver_first_name', models.CharField(max_length=50)),
                ('receiver_other_names', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_address', models.CharField(max_length=255)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_postal_code', models.CharField(max_length=20)),
                ('receiver_bank_address', models.CharField(max_length=255)),
                ('receiver_account_number', models.CharField(max_length=50)),
                ('receiver_iban', models.CharField(max_length=50)),
                ('receiver_amount_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('NGN', 'NGN')], max_length=3)),
                ('receiver_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_reason', models.CharField(max_length=255)),
            ],
        ),
    ]
