# Generated by Django 4.0 on 2024-07-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_enquiry', '0002_customerfx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_address', models.TextField()),
                ('person_landmark', models.CharField(max_length=100)),
                ('person_phone', models.CharField(max_length=15)),
                ('guarantor_name', models.CharField(max_length=100)),
                ('guarantor_address', models.TextField()),
                ('guarantor_landmark', models.CharField(max_length=100)),
                ('guarantor_phone', models.CharField(max_length=15)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_address', models.TextField()),
                ('supplier_phone', models.CharField(max_length=15)),
                ('amount_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('NGN', 'NGN')], max_length=3)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
