# Generated by Django 4.0 on 2024-08-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_alter_user_phone'),
        ('service_enquiry', '0004_customerfx_user_alter_procurement_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.user'),
            preserve_default=False,
        ),
    ]
