# Generated by Django 4.0 on 2024-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_enquiry', '0005_procurement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfx',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
