# Generated by Django 4.0 on 2024-08-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='tracking_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
